[theme]
base = 'light'
primaryColor = "#38a347"
backgroundColor = '#FFFFFF'
textColor = "#000000"
font = "sans serif"
buttonRadius ="large"


[client]
showErrorDetails = "stacktrace"
toolbarMode = "viewer"
showSidebarNavigation = true

